# Generated by Django 5.0.4 on 2024-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('field', models.CharField(max_length=100)),
            ],
        ),
    ]
