# Generated by Django 5.0.4 on 2024-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0007_alter_message_room_alter_message_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.CharField(blank=True, null=True),
        ),
    ]
