# Generated by Django 5.0.4 on 2024-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0008_alter_room_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
